version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: devops/Dockerfile.development
      args:
        - NODE_ENV=development
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: sh -c "yarn install --silent && yarn start:dev"

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5440:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=template

volumes:
  node_modules:
